[project]
name = "bbqs-ember-cookbook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.42.29",
    "matplotlib>=3.10.8",
    "pynwb>=3.1.3",
    "requests>=2.32.5",
]
